// Session Status Constants
export const SESSION_STATUS = {
  RAW: 'raw',
  TAGGED: 'tagged',
  SHARED: 'shared',
  SENT: 'sent'
};

// File Upload Constants
export const FILE_LIMITS = {
  MAX_SIZE_MB: 10,
  MAX_SIZE_BYTES: 10 * 1024 * 1024,
  ALLOWED_TYPES: ['image/jpeg', 'image/jpg', 'image/png'],
  ALLOWED_EXTENSIONS: ['.jpg', '.jpeg', '.png']
};

// Image Processing Constants
export const IMAGE_CONFIG = {
  THUMBNAIL_MAX_WIDTH: 300,
  THUMBNAIL_MAX_HEIGHT: 300,
  PREVIEW_MAX_WIDTH: 1200,
  PREVIEW_MAX_HEIGHT: 1200,
  QUALITY: 0.85
};

// Debug Event Types
export const DEBUG_EVENTS = {
  // Upload Events
  UPLOAD_START: 'UPLOAD_START',
  UPLOAD_SUCCESS: 'UPLOAD_SUCCESS',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  IMAGE_COMPRESSED: 'IMAGE_COMPRESSED',
  SESSION_CREATED: 'SESSION_CREATED',

  // Tagging Events
  TAG_ADDED: 'TAG_ADDED',
  TAG_MOVED: 'TAG_MOVED',
  TAG_SAVED: 'TAG_SAVED',
  TAG_ERROR: 'TAG_ERROR',
  TAG_SESSION_COMPLETE: 'TAG_SESSION_COMPLETE',

  // Share Events
  SHARE_START: 'SHARE_START',
  SHARE_SUCCESS: 'SHARE_SUCCESS',
  SHARE_ERROR: 'SHARE_ERROR',
  SHARE_TAGGED: 'SHARE_TAGGED',
  SHARE_UNTAGGED: 'SHARE_UNTAGGED',
  COMMENT_COPIED: 'COMMENT_COPIED',
  WATERMARK_APPLIED: 'WATERMARK_APPLIED',

  // Gallery Events
  GALLERY_LOAD: 'GALLERY_LOAD',
  GALLERY_REFRESH: 'GALLERY_REFRESH',
  GALLERY_ERROR: 'GALLERY_ERROR',
  SESSION_VIEWED: 'SESSION_VIEWED',
  SESSION_TOGGLED: 'SESSION_TOGGLED',
  SESSION_DELETED: 'SESSION_DELETED',

  // CRM Events
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DELIVERED: 'CUSTOMER_DELIVERED',
  CUSTOMER_SYNCED: 'CUSTOMER_SYNCED',
  CRM_UPDATE: 'CRM_UPDATE',
  CRM_SYNC_ERROR: 'CRM_SYNC_ERROR',

  // Delivery Events
  DELIVERY_QUEUED: 'DELIVERY_QUEUED',
  DELIVERY_START: 'DELIVERY_START',
  DELIVERY_SUCCESS: 'DELIVERY_SUCCESS',
  DELIVERY_FAIL: 'DELIVERY_FAIL',
  DELIVERY_RETRY: 'DELIVERY_RETRY',
  SEND_INITIATED: 'SEND_INITIATED',

  // Settings Events
  SETTINGS_SAVED: 'SETTINGS_SAVED',
  SETTINGS_LOADED: 'SETTINGS_LOADED',
  SETTINGS_ERROR: 'SETTINGS_ERROR',

  // System Events
  DB_INIT: 'DB_INIT',
  DB_ERROR: 'DB_ERROR',
  ROUTE_CHANGE: 'ROUTE_CHANGE'
};

// Tag Default Settings
export const TAG_DEFAULTS = {
  FONT_SIZE: 24,
  FONT_FAMILY: 'Arial, sans-serif',
  COLOR: '#FFFFFF',
  BACKGROUND_COLOR: 'rgba(0, 0, 0, 0.6)',
  POSITION_X: 50,
  POSITION_Y: 50
};

// Delivery Settings
export const DELIVERY_CONFIG = {
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 5000,
  TIMEOUT_MS: 30000
};

export default {
  SESSION_STATUS,
  FILE_LIMITS,
  IMAGE_CONFIG,
  DEBUG_EVENTS,
  TAG_DEFAULTS,
  DELIVERY_CONFIG
};
